server:
  port: 8080

spring:
  session:
    store-type: none

  redis:
    host: 127.0.0.1
    port: 6380
    pool:
      # 最大连接数（负值表示没有限制）
      max-active: 8
      # 最大阻塞等待时间（负值表示没有限制）
      max-wait: 1
      # 最大空闲链接
      max-idle: 8
      # 最小空闲链接
      min-idle: 0
      # 链接超时时间（毫秒）
    timeout: 0
